### ISSUE TITLE
Service "type" chart value unused

### ISSUE THREAD

**Issue by gregsmi** [broadinstitute/seqr-helm#14]
The values template (and readme) contain a configurable entry for "service.type" but it appears the actual value is hardcoded to NodePort

service.yaml
```
kind: Service
apiVersion: v1
...
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
```
